// <auto-generated />
using System;
using ForceApiCall;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForceApiCall.Migrations
{
    [DbContext(typeof(WorkplaceContext))]
    partial class WorkplaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ForceApiCall.SetupData", b =>
                {
                    b.Property<int>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("int");

                    b.Property<string>("setupDuration")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("setupEndTs")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("setupRate")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("setupStartTs")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("setupTimeDeviationAbs")
                        .HasColumnType("longtext");

                    b.Property<string>("setupTimeDeviationRel")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("targetStartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PrimaryId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Setups");
                });

            modelBuilder.Entity("ForceApiCall.Workplace", b =>
                {
                    b.Property<int>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Id")
                        .HasColumnType("longtext");

                    b.Property<string>("TargetSetupTime")
                        .HasColumnType("longtext");

                    b.HasKey("PrimaryId");

                    b.ToTable("Workplaces");
                });

            modelBuilder.Entity("ForceApiCall.SetupData", b =>
                {
                    b.HasOne("ForceApiCall.Workplace", "Workplace")
                        .WithMany("Setups")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("ForceApiCall.Workplace", b =>
                {
                    b.Navigation("Setups");
                });
#pragma warning restore 612, 618
        }
    }
}
